name: Increment and Create Release
on:
  push:
    paths:
      - "tester.txt"
    branches:
      - "**"
jobs:
  increment-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Get Latest Release Version
        id: get_version
        run: |
          RELEASE_VERSION=$(gh release view  --json tagName --jq '.tagName')
          echo "::set-output name=version::${RELEASE_VERSION}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
      - name: Increment Version
        id: increment_version
        run: |
          PREVIOUS_VERSION="${{ steps.get_version.outputs.version }}"
          IFS='.' read -ra PARTS <<< "$PREVIOUS_VERSION"
          MAJOR="${PARTS[0]}"
          MINOR="${PARTS[1]}"
          PATCH="${PARTS[2]}"
          PATCH=$((PATCH + 1))
          NEW_VERSION="${MAJOR}.${MINOR}.${PATCH+1}"
          echo "::set-output name=version::${NEW_VERSION}"
      - name: Create Release
        run: |
          IFS="" echo "${{github.event.head_commit.message}}"
          read -ra message <<< "${{github.event.head_commit.message}}"
          echo "${message[0]}"
          echo "${message[@]:1}"
          # gh release create ${{ steps.increment_version.outputs.version }} -t "${{ steps.increment_version.outputs.version }}"
        env:
          GH_TOKEN: ${{ secrets.PAT }}
